package com.example.sda.services;

import com.example.sda.dao.UserDAO;
import com.example.sda.models.User;
import com.example.sda.enums.UserRole;
import org.mindrot.jbcrypt.BCrypt; // Import the jBCrypt library
import com.example.sda.utils.AlertHelper; // Keeping this import if used elsewhere

/**
 * Handles all business logic related to user authentication (registration, login, etc.).
 */
public class AuthService {
    private final UserDAO userDAO;

    public AuthService() {
        this.userDAO = new UserDAO();
    }

    /**
     * Hashes the raw password using BCrypt.
     * The salt is automatically generated by BCrypt.gensalt().
     * @param password The raw password string.
     * @return The resulting BCrypt hash string.
     */
    private String hashPassword(String password) {
        // We use BCrypt.hashpw(password, BCrypt.gensalt()) for production-grade security.
        return BCrypt.hashpw(password, BCrypt.gensalt());
    }

    /**
     * Checks if a raw password matches a hashed password using BCrypt.
     * @param candidatePassword The raw password entered by the user.
     * @param hashedPassword The hash stored in the database.
     * @return true if they match, false otherwise.
     */
    public boolean checkPassword(String candidatePassword, String hashedPassword) {
        // BCrypt handles the extraction of the salt and the comparison safely.
        return BCrypt.checkpw(candidatePassword, hashedPassword);
    }

    /**
     * Authenticates a user based on email and password.
     * @param email The user's email.
     * @param password The raw password entered by the user.
     * @return The User object if authentication is successful, otherwise null.
     */
    public User authenticate(String email, String password) {
        // 1. Fetch user by email
        User user = userDAO.getUserByEmail(email);

        // 2. Check if user exists and if password matches the stored hash
        if (user != null && checkPassword(password, user.getPassword())) {
            // Password matches, authentication successful
            return user;
        }

        // Authentication failed
        return null;
    }

    /**
     * Registers a new user into the system.
     * @param username The full name of the user.
     * @param email The user's email (must be unique).
     * @param password The raw password.
     * @param role The user's role (Student or Alumni).
     * @return true if registration was successful, false otherwise.
     * @throws IllegalArgumentException if the email already exists.
     */
    public boolean registerUser(String username, String email, String password, UserRole role) throws IllegalArgumentException {

        // 1. Check if user already exists
        if (userDAO.getUserByEmail(email) != null) {
            throw new IllegalArgumentException("Error: An account with this email already exists.");
        }

        // 2. Hash the password using BCrypt
        String hashedPassword = hashPassword(password);

        // 3. Create the User model
        User newUser = new User(username, email, hashedPassword, role);

        // 4. Save to the database
        int newId = userDAO.saveUser(newUser);

        // Check if the save operation was successful
        return newId != -1;
    }
}